FROM python:3.9

# Instalar dependencias del sistema necesarias para MariaDB (compatible con MySQL)
RUN apt-get update && apt-get install -y \
    libmariadb-dev-compat \
    libmariadb-dev \
    build-essential

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de requisitos y el código de la aplicación
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app

# Exponer el puerto para la aplicación
EXPOSE 5000

# Ejecutar la aplicación con Gunicorn, leyendo el puerto de la variable de entorno
CMD ["gunicorn", "--bind", "0.0.0.0:$PORT", "app:app"]
