# Usar una imagen base de Python
FROM python:3.9

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de requisitos y la aplicación al contenedor
COPY requirements.txt .
COPY app.py .
COPY migrate.py .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto de la aplicación
EXPOSE 5000

# Comando para ejecutar las migraciones y luego iniciar la aplicación
CMD ["sh", "-c", "python migrate.py && python app.py"]