FROM python:3.9

# Instalar dependencias del sistema necesarias para MySQL
RUN apt-get update && apt-get install -y \
    mysql-server \
    libmysqlclient-dev

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de requisitos y el código de la aplicación
COPY ./requirements.txt /app
COPY ./app.py /app
COPY ./migrate.py /app

# Instalar las dependencias de Python
RUN pip install -r requirements.txt

# Copiar el archivo de configuración de MySQL
COPY ./my.cnf /etc/mysql/my.cnf

# Copiar el script de inicialización de la base de datos
COPY ./init_db.sh /docker-entrypoint-initdb.d/

# Asegurarse de que el script de inicialización sea ejecutable
RUN chmod +x /docker-entrypoint-initdb.d/init_db.sh

# Exponer puertos necesarios
EXPOSE 5000 3306

# Ejecutar el servidor MySQL y luego la aplicación Flask
CMD service mysql start && bash /docker-entrypoint-initdb.d/init_db.sh && python migrate.py && python app.py
